### ISSUE TITLE
Update example for newest API

### ISSUE THREAD

**Issue by raffomania** [PistonDevelopers/sprite#126]
The example in the piston-examples repo doesn't seem to be up to date with the current API.

When initializing the Scene as shown in the example, I get the following error:

```
wrong number of type arguments: expected 1, found 0
```

I think I have to specify a Texture type, but am not exactly sure on how to get this to work. An up-to-date example would help me a lot!

**Comment by radix** [comment]
I can't reproduce this -- I assume the example has been updated since January, so this ticket can probably be closed. for the record, the current release of piston2d-sprite is 0.30.0 and that is the version that piston-examples is using.

**Comment by raffomania** [comment]
it probably is outdated.
