### ISSUE TITLE
Type error calling sprite.draw in a function

### ISSUE THREAD

**Issue by wjlroe** [PistonDevelopers/sprite#133]
I'm having a weird type error when I extract my draw loop out of main() into its own function:

```rust

fn run<I: ImageSize>(window: &mut PistonWindow, scene: &Scene<I>) {
    while let Some(e) = window.next() {
        window.draw_2d(&e, |c, g| {
            clear([1.0; 4], g);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [0.0, 0.0, 100.0, 100.0],
                      c.transform,
                      g);
            scene.draw(c.transform, g);
        });
    }
}

...

fn main() {
...
    run(&mut window, &scene);
...
```

And I get:

```
src/main.rs:17:19: 17:23 error: type mismatch resolving `<gfx_graphics::back_end::GfxGraphics<'_, gfx_device_gl::Resources, gfx_device_gl::command::CommandBuffer> as graphics::graphics::Graphics>::Texture == I`:
 expected struct `gfx_texture::Texture`,
    found type parameter [E0271]
src/main.rs:17             scene.draw(c.transform, g);
                                 ^~~~
src/main.rs:17:19: 17:23 help: run `rustc --explain E0271` to see a detailed explanation
```

Can anyone provide a clue as to how to write this function so it doesn't cause the type checker to shout at me? It's as if `g` from `draw_2d` is not understood somehow when I've extracted this out.

**Comment by bvssvni** [comment]
Those generic errors can be tricky. Can you paste the code to `scene.draw`?

**Comment by wjlroe** [comment]
Certainly, the code to `scene.draw` is:

```rust
    pub fn draw<B: Graphics<Texture = I>>(&self, t: Matrix2d, b: &mut B) {
        for child in &self.children {
            child.draw(t, b);
        }
    }
```

and the type of `PistonWindow.draw_2d` is:

```rust
pub fn draw_2d<E, F, U>(&mut self, e: &E, f: F) -> Option<U> where
        E: GenericEvent,
        F: FnOnce(Context, &mut G2d) -> U
    {
```

**Comment by bvssvni** [comment]
I think I know what is wrong. You have a generic parameter `I` on the `Scene` and try to call a method where a concrete type is expected.

Change the function to:

```rust
use piston_window::G2dTexture;

fn run(window: &mut PistonWindow, scene: &Scene<G2dTexture>) { ... }
```

**Comment by wjlroe** [comment]
That was it! I was vaguely worried I was committing some sort of type erasure but my Rust isn't up to understanding exactly how or what the actual type should have been. Many thanks for your help. I will get back to reading the early access Rust Programming book to prevent these sorts of things cropping up again for me.
