### ISSUE TITLE
Error when trying to "cargo run"

### ISSUE THREAD

**Issue by sunnystormy** [PistonDevelopers/sprite#135]
I keep getting this message when trying to "cargo run" the code:

`error: a bin target must be available for "cargo run"`

I'm using Rust 1.9 on GNU/Linux. Please let me know if I'm missing something.

**Comment by tafia** [comment]
Sprite is a *library*, not a binary. 
If you want to use it you must import it (the crate) in your binary project through cargo.toml, if you want to work on it you must use `cargo build`, `cargo test` and eventually `cargo bench`

**Comment by sunnystormy** [comment]
Phew!

Well, that explains it. I've been testing its usage on the "piston-examples" repo, but thought this was just an isolated example. Thank you for clearing that up. :)
