### ISSUE TITLE
API docs for piston2d-sprite don't seem to be published anywhere

### ISSUE THREAD

**Issue by radix** [PistonDevelopers/sprite#139]
It would be nice if there were an online reference to this library (probably at docs.piston.rs?)

**Comment by bvssvni** [comment]
Or https://docs.rs/piston2d-sprite/0.30.0/sprite/. I like docs.rs.

**Comment by radix** [comment]
Thanks! I'll submit a PR to the README :)

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/sprite/pull/141
