### ISSUE TITLE
Use Behavior for sprite animations

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/sprite#25]
See https://github.com/PistonDevelopers/sprite/issues/6
See https://github.com/PistonDevelopers/sprite/issues/8

The `Behavior` is powerful enough to describe sprite animations, including delays, loops etc. This means that if we had an editor for a scene we could modify the behavior and animations through the same tools. The problem we have to solve is coming up with a design that is serializable. `Rc<Texture>` is not serializable.

One idea is to use hidden sprites for animation, such that we can use uuid to point to the sprite. This can be specified in the `Behavior<Animation>` structure, as `Animation(SetFrame(WholeFrame(uuid)))`, `Animation(SetFrame(SubFrame(uuid, SourceRectangle)))` or `Animation(SetFrame(DefaultFrame))`.

All sprites got a default frame. After displaying a temporary frame, you can set it back to default by using `Animation(SetFrame(DefaultFrame))`. Default frames means you don't have to add a behavior in order to display something.

With https://github.com/PistonDevelopers/sprite/pull/23 we will get a step closer to unifying actions and sprite animations.

**Comment by bvssvni** [comment]
I think a better route than using serialization is to traverse the tree, print out the structure and parse it with piston_meta.

**Comment by radix** [comment]
Is this ticket still valid? I see that the piston-example for sprite uses ai_behavior already.

**Comment by bvssvni** [comment]
You're right. Closing.
