### ISSUE TITLE
Won't compile due to use of box over Box::new

### ISSUE THREAD

**Issue by agmcleod** [PistonDevelopers/sprite#62]
Attempting to run one of the piston examples, i get a few compile errors in piston-sprite2d

    src/animation.rs:163:30: 163:60 error: box expression syntax is experimental in alpha release; you can call `Box::new` instead.
    src/animation.rs:163                 EaseState(f, box animation.to_state(sprite))
                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:163:30: 163:60 help: add #![feature(box_syntax)] to the crate attributes to enable
    src/animation.rs:163                 EaseState(f, box animation.to_state(sprite))
                                                        ^~~~
    src/animation.rs:242:21: 242:56 error: box pattern syntax is experimental in alpha release
    src/animation.rs:242                     box MoveState(t, bx, by, cx, cy, d) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:242:21: 242:56 help: add #![feature(box_syntax)] to the crate attributes to enable
    src/animation.rs:242                     box MoveState(t, bx, by, cx, cy, d) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:247:21: 247:48 error: box pattern syntax is experimental in alpha release
    src/animation.rs:247                     box RotateState(t, b, c, d) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:247:21: 247:48 help: add #![feature(box_syntax)] to the crate attributes to enable
    src/animation.rs:247                     box RotateState(t, b, c, d) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:251:21: 251:57 error: box pattern syntax is experimental in alpha release
    src/animation.rs:251                     box ScaleState(t, bx, by, cx, cy, d) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:251:21: 251:57 help: add #![feature(box_syntax)] to the crate attributes to enable
    src/animation.rs:251                     box ScaleState(t, bx, by, cx, cy, d) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:255:21: 255:46 error: box pattern syntax is experimental in alpha release
    src/animation.rs:255                     box FadeState(t, b, c, d) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:255:21: 255:46 help: add #![feature(box_syntax)] to the crate attributes to enable
    src/animation.rs:255                     box FadeState(t, b, c, d) => {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
    src/animation.rs:274:44: 274:53 error: box expression syntax is experimental in alpha release; you can call `Box::new` instead.
    src/animation.rs:274                         (Some(EaseState(f, box state)),
                                                                    ^~~~~~~~~
    src/animation.rs:274:44: 274:53 help: add #![feature(box_syntax)] to the crate attributes to enable
    src/animation.rs:274                         (Some(EaseState(f, box state)),

I'd be happy to fork and make a pull request to change via the error message. But not sure if there's something else I should be doing instead :)

I'm running the latest nightly:

    rustc 1.0.0-nightly (3d0d9bb6f 2015-01-12 22:56:20 +0000)

**Comment by agmcleod** [comment]
Thanks.

**Comment by zummenix** [comment]
Should work now but sprite example broken too.

**Comment by agmcleod** [comment]
Yep, added the feature attribute. From here I think i can manage.
