### ISSUE TITLE
Question, any reason we pass owner ship of Uuid to scene.child() instead of immutable reference?

### ISSUE THREAD

**Issue by agmcleod** [PistonDevelopers/sprite#72]
Probably because I'm new to rust still, and i don't understand the reasoning. But having used so many GC languages lately, I know to avoiding creating new temp objects in mid game loop is key. So i'm wondering if it's possible to refactor the `child(&self, id: Uuid) -> Option<&Sprite<I>>` to accept an immutable reference instead. Simplifying use of the api.

**Comment by bvssvni** [comment]
That would be nice!

**Comment by sinistersnare** [comment]
Haha I was gonna make this issue like a week ago. I can make the fix right now.
